-- Resolución Ejercicio 1
SELECT c.NOMBRE, c.CUENTA, SUM(m.IMPORTE) AS SALDO
FROM CLIENTES c
JOIN MOVCUEN m ON c.CUENTA = m.CUENTA
GROUP BY c.NOMBRE, c.CUENTA;

-- Resolución Ejercicio 2
SELECT FECHA, OPERACIÓN, IMPORTE
FROM MOVCUEN
WHERE FECHA BETWEEN '2016-12-01' AND '2016-12-31';